on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"

name: forecast

jobs:
  forecast:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
    
      - uses: r-lib/actions/setup-renv@v2

      - name: Install cmdstan
        run: |
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Forecast
        run: Rscript main.R

      - name: Upload forecast
        uses: actions/upload-artifact@v2
        with:
          name: forecast
          retention-days: 14
          path: data-processed

      - name: Upload figures
        uses: actions/upload-artifact@v2
        with:
          name: figures
          retention-days: 14
          path: figures

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          retention-days: 14
          path: logs
